apiVersion: v1
entries:
  strlab-operator:
  - apiVersion: v2
    appVersion: 1.2.3
    created: "2026-05-04T06:30:58.281158281Z"
    description: Kubernetes Operator for Strlab Studio
    digest: 4a275d66b05dfc615dc2a62db473d1e6ccf1dea3ee0ed2324e56522911001521
    home: https://github.com/coded-streams/strlabstudio-operator
    keywords:
    - flink
    - sql
    - streaming
    - kubernetes
    - operator
    - strlabstudio
    maintainers:
    - email: nestorabiawuh@gmail.com
      name: Nestor A. A
    name: strlab-operator
    type: application
    urls:
    - https://coded-streams.github.io/strlabstudio-operator/charts/strlab-operator-1.2.3.tgz
    version: 1.2.3
generated: "2026-05-04T06:30:58.280743629Z"
