apiVersion: v1
entries:
  strlab-operator:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-05-04T05:06:29.70126417Z"
    description: Kubernetes Operator for Strlab Studio
    digest: 8491444d89199db81de3eade2513ad1d0a1166f6cec0eb09f5547852990a14f2
    home: https://github.com/coded-streams/strlab-kube-operator
    keywords:
    - flink
    - sql
    - streaming
    - kubernetes
    - operator
    - strlabstudio
    maintainers:
    - email: nestorabiawuh@gmail.com
      name: Nestor A. A
    name: strlab-operator
    type: application
    urls:
    - https://coded-streams.github.io/strlabstudio-operator/charts/strlab-operator-1.2.0.tgz
    version: 1.2.0
generated: "2026-05-04T05:06:29.700702674Z"
