apiVersion: v1
entries:
  strlab-operator:
  - apiVersion: v2
    appVersion: 1.2.2
    created: "2026-05-04T06:21:34.439707837Z"
    description: Kubernetes Operator for Strlab Studio
    digest: b22cc32e5b41cc7dd53d8871f3858fb4567433f0670a14eca6ac287a766fe1b7
    home: https://github.com/coded-streams/strlabstudio-operator
    keywords:
    - flink
    - sql
    - streaming
    - kubernetes
    - operator
    - strlabstudio
    maintainers:
    - email: nestorabiawuh@gmail.com
      name: Nestor A. A
    name: strlab-operator
    type: application
    urls:
    - https://coded-streams.github.io/strlabstudio-operator/charts/strlab-operator-1.2.2.tgz
    version: 1.2.2
generated: "2026-05-04T06:21:34.43936113Z"
