apiVersion: v2
name: strlab-operator
description: Kubernetes Operator for Str:::lab Studio
type: application
version: "1.0.0"
appVersion: "1.0.0"
keywords: [flink, sql, streaming, kubernetes, operator, strlabstudio]
home: https://github.com/coded-streams/strlab-kube-operator
maintainers:
  - name: Nestor A. A
    email: nestorabiawuh@gmail.com