image:
  repository: codedstreams/strlab-kube-operator
  tag: latest
  pullPolicy: IfNotPresent

operatorNamespace: strlab-system

installCRD: true

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"